databases:
- cluster_name: portfolio-ahmed
  db_name: defaultdb
  db_user: doadmin
  engine: PG
  name: portfolio-ahmed
  production: true
  version: "12"
domains:
- domain: yes.ahmedwill.cyou
  type: PRIMARY
  zone: ahmedwill.cyou
- domain: www.yes.ahmedwill.cyou
  type: ALIAS
  zone: ahmedwill.cyou
egress:
  type: DEDICATED_IP
features:
- buildpack-stack=ubuntu-18
ingress:
  rules:
  - component:
      name: django-app-portfolio-static
    match:
      path:
        prefix: /static
  - component:
      name: django-app-portfolio
    match:
      path:
        prefix: /
name: django-app-portfolio
region: nyc
services:
- autoscaling:
    max_instance_count: 3
    metrics:
      cpu:
        percent: 5
    min_instance_count: 2
  environment_slug: python
  github:
    branch: master
    deploy_on_push: true
    repo: abuttDO/django-app
  http_port: 80
  instance_size_slug: professional-1l
  name: django-app-portfolio
  run_command: gunicorn --worker-tmp-dir /dev/shm portfolio.wsgi
  source_dir: /
static_sites:
- environment_slug: python
  github:
    branch: master
    deploy_on_push: true
    repo: abuttDO/django-app
  name: django-app-portfolio-static
  output_dir: static
  source_dir: /